name: Backend CI/CD (skip tests if no key)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write   # needed for GHCR push

env:
  PYTHON_VERSION: "3.13"
  IMAGE_NAME: ghcr.io/${{ github.repository }}/repairmen-chatbot

jobs:
  # --- Probe secrets & expose booleans as job outputs ---
  check-secrets:
    name: Check secrets
    runs-on: ubuntu-latest
    outputs:
      has_openai_key: ${{ steps.keys.outputs.has_openai_key }}
      has_railway: ${{ steps.keys.outputs.has_railway }}
    steps:
      - id: keys
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          if [ -n "$OPENAI_API_KEY" ]; then echo "has_openai_key=true" >> "$GITHUB_OUTPUT"; else echo "has_openai_key=false" >> "$GITHUB_OUTPUT"; fi
          if [ -n "$RAILWAY_TOKEN" ]; then echo "has_railway=true" >> "$GITHUB_OUTPUT"; else echo "has_railway=false" >> "$GITHUB_OUTPUT"; fi

  build:
    name: Install deps
    runs-on: ubuntu-latest
    needs: check-secrets
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Optional) Lint
      # - name: Ruff
      #   run: pip install ruff && ruff check .

  test:
    name: Run tests (only if OPENAI_API_KEY provided)
    runs-on: ubuntu-latest
    needs: [build, check-secrets]
    if: needs.check-secrets.outputs.has_openai_key == 'true'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest -q

  docker:
    name: Build & Push Docker (GHCR)
    runs-on: ubuntu-latest
    needs: [build]   # don't block on tests; they may be skipped
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-railway:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: [docker, check-secrets]
    if: github.ref == 'refs/heads/main' && needs.check-secrets.outputs.has_railway == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Trigger Railway deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
        run: |
          railway login --token "$RAILWAY_TOKEN"
          railway link --project "$RAILWAY_PROJECT_ID"
          railway up --service "$RAILWAY_SERVICE_ID" --ci